package com.kadziela.games.bridge.model.enumeration;

public enum ValidBidOption 
{
	ONE_CLUBS, ONE_DIAMONDS, ONE_HEARTS, ONE_SPADES, ONE_NO_TRUMP,
	TWO_CLUBS, TWO_DIAMONDS, TWO_HEARTS, TWO_SPADES, TWO_NO_TRUMP,
	THREE_CLUBS, THREE_DIAMONDS, THREE_HEARTS, THREE_SPADES, THREE_NO_TRUMP,
	FOUR_CLUBS, FOUR_DIAMONDS, FOUR_HEARTS, FOUR_SPADES, FOUR_NO_TRUMP,
	FIVE_CLUBS, FIVE_DIAMONDS, FIVE_HEARTS, FIVE_SPADES, FIVE_NO_TRUMP,
	SIX_CLUBS, SIX_DIAMONDS, SIX_HEARTS, SIX_SPADES, SIX_NO_TRUMP,
	SEVEN_CLUBS, SEVEN_DIAMONDS, SEVEN_HEARTS, SEVEN_SPADES, SEVEN_NO_TRUMP,
	DOUBLE, REDOUBLE, PASS;
}